const QUESTION_TIMEOUT_MINUTES = 10;
const SECONDS_PER_MINUTE = 60;
const MS_PER_SECOND = 1000;

export const COLD_INIT_WORKER_CONCURRENCY_MAX = 6;
export const COLD_INIT_QUESTION_TIMEOUT_MS = QUESTION_TIMEOUT_MINUTES * SECONDS_PER_MINUTE * MS_PER_SECOND;
export const COLD_INIT_QUESTION_GROUP_MIN = 1;
export const COLD_INIT_QUESTION_GROUP_MAX = 12;
export const COLD_INIT_DESIGN_EXCERPT_CHARS = 600;
export const COLD_INIT_README_EXCERPT_CHARS = 1200;
export const COLD_INIT_RUN_ID_PREFIX = "cold-init";
export const COLD_INIT_DEFAULT_PROJECT_TYPE = "generic";
