export interface IndexEntry {
  readonly name: string;
  readonly description: string;
  readonly hits: number;
  readonly lastUpdated: string;
  readonly deprecated: boolean;
}

const HEADER = "# Skills\n\nThis file is auto-generated by the Skill Autopilot. Do not edit by hand.\n";
const EMPTY = "(no skills yet)";
const DEPRECATED_LABEL = " (deprecated)";

function renderRow(entry: IndexEntry): string {
  const status = entry.deprecated ? DEPRECATED_LABEL : "";
  return `- **${entry.name}**${status} hits=${entry.hits} updated=${entry.lastUpdated} - ${entry.description}`;
}

export function renderIndexMd(entries: readonly IndexEntry[]): string {
  if (entries.length === 0) return `${HEADER}\n${EMPTY}\n`;

  const sorted = [...entries].sort((left, right) => left.name.localeCompare(right.name));
  const rows = sorted.map((entry) => renderRow(entry)).join("\n");

  return `${HEADER}\n${rows}\n`;
}
